# Generated by Django 5.2.17 on 2026-09-19 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Chủ tổ chức'), ('manager', 'Điều phối viên'), ('volunteer', 'Tình nguyện viên')], default='volunteer', max_length=20),
        ),
    ]
