# Generated by Django 5.2.17 on 2026-09-20 00:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_alter_organizationmembership_role'),
        ('rescue', '0006_notification_target_url_alter_notification_kind_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('animal_type', models.CharField(choices=[('dog', 'Chó'), ('cat', 'Mèo'), ('bird', 'Chim'), ('other', 'Khác')], max_length=20)),
                ('breed', models.CharField(blank=True, max_length=120)),
                ('sex', models.CharField(choices=[('male', 'Đực'), ('female', 'Cái'), ('unknown', 'Chưa xác định')], default='unknown', max_length=20)),
                ('age_group', models.CharField(choices=[('baby', 'Sơ sinh'), ('young', 'Nhỏ tuổi'), ('adult', 'Trưởng thành'), ('senior', 'Lớn tuổi'), ('unknown', 'Chưa xác định')], default='unknown', max_length=20)),
                ('estimated_age', models.CharField(blank=True, max_length=80)),
                ('size', models.CharField(choices=[('small', 'Nhỏ'), ('medium', 'Vừa'), ('large', 'Lớn'), ('unknown', 'Chưa xác định')], default='unknown', max_length=20)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('temperament', models.TextField()),
                ('health_status', models.TextField()),
                ('vaccination_status', models.CharField(choices=[('unknown', 'Chưa xác định'), ('not_started', 'Chưa tiêm'), ('partial', 'Đã tiêm một phần'), ('complete', 'Đã tiêm đầy đủ')], default='unknown', max_length=20)),
                ('is_neutered', models.BooleanField(default=False)),
                ('special_needs', models.TextField(blank=True)),
                ('location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('available', 'Đang tìm gia đình'), ('pending', 'Đang xét duyệt'), ('hold', 'Tạm dừng nhận đơn'), ('adopted', 'Đã được nhận nuôi'), ('not_available', 'Chưa sẵn sàng')], default='available', max_length=20)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adopted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_adoption_profiles', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_profiles', to='organizations.rescueorganization')),
                ('rescue_case', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adoption_profile', to='rescue.rescuecase')),
            ],
            options={
                'ordering': ('-published_at',),
            },
        ),
        migrations.CreateModel(
            name='AnimalProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='adoption_animals/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg', 'png', 'webp'))])),
                ('caption', models.CharField(blank=True, max_length=180)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='adoptions.animalprofile')),
            ],
            options={
                'ordering': ('uploaded_at',),
            },
        ),
        migrations.CreateModel(
            name='AdoptionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('housing_type', models.CharField(choices=[('house', 'Nhà riêng'), ('apartment', 'Căn hộ'), ('rental', 'Nhà thuê'), ('other', 'Khác')], max_length=20)),
                ('has_children', models.BooleanField(default=False)),
                ('other_pets', models.TextField(blank=True)),
                ('pet_experience', models.TextField(blank=True)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Đang chờ'), ('reviewing', 'Đang xét duyệt'), ('approved', 'Đã chấp thuận'), ('rejected', 'Không phù hợp'), ('withdrawn', 'Đã rút đơn')], default='pending', max_length=20)),
                ('review_note', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_applications', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_adoption_applications', to=settings.AUTH_USER_MODEL)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='adoptions.animalprofile')),
            ],
            options={
                'ordering': ('-submitted_at',),
                'constraints': [models.UniqueConstraint(fields=('animal', 'applicant'), name='unique_animal_adoption_applicant')],
            },
        ),
    ]
