# Generated by Django 5.2.17 on 2026-09-20 07:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0001_initial'),
        ('organizations', '0002_alter_organizationmembership_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionapplication',
            name='agrees_follow_up',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='agrees_no_resale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='agrees_return_to_organization',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='identity_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='pledge_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AdoptionPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Đang theo dõi'), ('needs_attention', 'Cần kiểm tra'), ('flagged', 'Nghi ngờ vi phạm'), ('returned', 'Đã bàn giao lại'), ('closed', 'Đã kết thúc theo dõi')], default='active', max_length=24)),
                ('placed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('next_follow_up_on', models.DateField(blank=True, null=True)),
                ('last_follow_up_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('manager_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adopter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adoption_placements', to=settings.AUTH_USER_MODEL)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placements', to='adoptions.animalprofile')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='placement', to='adoptions.adoptionapplication')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adoption_placements', to='organizations.rescueorganization')),
            ],
            options={
                'ordering': ('next_follow_up_on', '-placed_at'),
            },
        ),
        migrations.CreateModel(
            name='AdoptionFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_method', models.CharField(choices=[('phone', 'Điện thoại'), ('video', 'Gọi video'), ('home_visit', 'Thăm tại nhà'), ('message', 'Tin nhắn'), ('other', 'Khác')], max_length=20)),
                ('outcome', models.CharField(choices=[('well', 'Đang được chăm sóc tốt'), ('needs_attention', 'Cần hỗ trợ thêm'), ('unreachable', 'Không liên lạc được'), ('suspected_resale', 'Nghi ngờ mua bán/chuyển nhượng'), ('returned', 'Đã bàn giao lại tổ chức')], max_length=24)),
                ('notes', models.TextField()),
                ('contacted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_adoption_follow_ups', to=settings.AUTH_USER_MODEL)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='adoptions.adoptionplacement')),
            ],
            options={
                'ordering': ('-contacted_at',),
            },
        ),
        migrations.CreateModel(
            name='AdoptionSafetyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('sale_listing', 'Phát hiện rao bán'), ('unauthorized_transfer', 'Tự ý chuyển cho người khác'), ('neglect', 'Có dấu hiệu bỏ bê/ngược đãi'), ('lost_contact', 'Không thể liên lạc người nhận nuôi'), ('other', 'Vấn đề khác')], max_length=30)),
                ('description', models.TextField()),
                ('evidence_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Chờ xác minh'), ('reviewing', 'Đang xác minh'), ('confirmed', 'Đã xác nhận vi phạm'), ('dismissed', 'Không đủ căn cứ')], default='pending', max_length=20)),
                ('review_note', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='safety_reports', to='adoptions.animalprofile')),
                ('placement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_reports', to='adoptions.adoptionplacement')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_adoption_safety_reports', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_adoption_safety_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-submitted_at',),
            },
        ),
        migrations.CreateModel(
            name='AdoptionRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_adoption_restrictions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, help_text='Để trống nếu hạn chế áp dụng trên toàn hệ thống.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adoption_restrictions', to='organizations.rescueorganization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_restrictions', to=settings.AUTH_USER_MODEL)),
                ('source_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restrictions', to='adoptions.adoptionsafetyreport')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='adoptionplacement',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('animal',), name='unique_active_animal_placement'),
        ),
        migrations.AddConstraint(
            model_name='adoptionrestriction',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', False)), fields=('user', 'organization'), name='unique_user_org_adoption_restriction'),
        ),
        migrations.AddConstraint(
            model_name='adoptionrestriction',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', True)), fields=('user',), name='unique_global_adoption_restriction'),
        ),
    ]
