# Generated by Django 5.2.17 on 2026-09-28 09:27

import calendar
from datetime import date

import django.db.models.deletion
from django.db import migrations, models


def _add_months(value, months):
    target_index = value.month - 1 + months
    year = value.year + target_index // 12
    month = target_index % 12 + 1
    day = min(value.day, calendar.monthrange(year, month)[1])
    return date(year, month, day)


def create_existing_schedules(apps, schema_editor):
    Placement = apps.get_model("adoptions", "AdoptionPlacement")
    CheckIn = apps.get_model("adoptions", "AdoptionCheckInRequest")
    rows = []
    placements = list(Placement.objects.all())
    for placement in placements:
        placed_on = placement.placed_at.date()
        for month in (1, 2, 3):
            rows.append(
                CheckIn(
                    placement_id=placement.pk,
                    milestone_month=month,
                    due_on=_add_months(placed_on, month),
                )
            )
        placement.next_follow_up_on = _add_months(placed_on, 1)
    CheckIn.objects.bulk_create(rows, ignore_conflicts=True)
    if placements:
        Placement.objects.bulk_update(placements, ("next_follow_up_on",))


class Migration(migrations.Migration):

    dependencies = [
        ("adoptions", "0002_adoptionapplication_agrees_follow_up_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdoptionCheckInRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "milestone_month",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Sau 1 tháng"),
                            (2, "Sau 2 tháng"),
                            (3, "Sau 3 tháng"),
                        ]
                    ),
                ),
                ("due_on", models.DateField(db_index=True)),
                ("notification_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "care_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("in_care", "Pet vẫn đang ở cùng tôi"),
                            ("needs_support", "Tôi cần hỗ trợ chăm sóc"),
                            ("return_request", "Tôi cần bàn giao lại cho tổ chức"),
                            ("missing", "Pet đang bị thất lạc"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "wellbeing",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("good", "Khỏe mạnh, hòa nhập tốt"),
                            ("stable", "Ổn định nhưng còn cần thời gian"),
                            ("concerning", "Có dấu hiệu cần được tư vấn"),
                            ("urgent", "Đang có vấn đề khẩn cấp"),
                        ],
                        max_length=20,
                    ),
                ),
                ("care_summary", models.TextField(blank=True)),
                ("health_changes", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "placement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="check_in_requests",
                        to="adoptions.adoptionplacement",
                    ),
                ),
            ],
            options={
                "ordering": ("due_on", "milestone_month"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("placement", "milestone_month"),
                        name="unique_placement_followup_milestone",
                    )
                ],
            },
        ),
        migrations.RunPython(create_existing_schedules, migrations.RunPython.noop),
    ]
