# Generated by Django 5.2.17 on 2026-09-21

import django.core.validators
import django.db.models.deletion
import support.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supportmessage",
            name="body",
            field=models.TextField(blank=True, default="", max_length=2000),
        ),
        migrations.CreateModel(
            name="SupportAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="support_attachments/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=(
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "webp",
                                    "gif",
                                    "mp4",
                                    "webm",
                                    "mov",
                                )
                            ),
                            support.models.validate_support_attachment_size,
                        ],
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("image", "Ảnh"), ("video", "Video")],
                        max_length=10,
                    ),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=100)),
                ("size", models.PositiveBigIntegerField()),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="support.supportmessage",
                    ),
                ),
            ],
            options={"ordering": ("uploaded_at", "pk")},
        ),
    ]
