# Generated by Django 5.2.17 on 2026-09-28 03:18

import django.core.validators
import donations.storage
import shutil
from pathlib import Path

from django.conf import settings
from django.db import migrations, models


def _relocate_files(apps, source_root, destination_root):
    file_fields = (
        (apps.get_model("donations", "Donation"), "proof"),
        (apps.get_model("donations", "CampaignExpense"), "receipt"),
    )
    source_root = Path(source_root).resolve()
    destination_root = Path(destination_root).resolve()
    for model, field_name in file_fields:
        for item in model.objects.exclude(**{field_name: ""}).iterator():
            relative_name = getattr(item, field_name).name
            source = (source_root / relative_name).resolve()
            destination = (destination_root / relative_name).resolve()
            if source_root not in source.parents or destination_root not in destination.parents:
                continue
            if not source.is_file():
                continue
            destination.parent.mkdir(parents=True, exist_ok=True)
            if destination.exists():
                source.unlink()
            else:
                shutil.move(str(source), str(destination))


def move_donation_documents_private(apps, schema_editor):
    _relocate_files(
        apps,
        settings.MEDIA_ROOT,
        settings.PRIVATE_DONATION_MEDIA_ROOT,
    )


def restore_donation_documents_public(apps, schema_editor):
    _relocate_files(
        apps,
        settings.PRIVATE_DONATION_MEDIA_ROOT,
        settings.MEDIA_ROOT,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            move_donation_documents_private,
            restore_donation_documents_public,
        ),
        migrations.AlterField(
            model_name='campaignexpense',
            name='receipt',
            field=models.FileField(blank=True, storage=donations.storage.PrivateDonationStorage(), upload_to='campaign_receipts/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg', 'png', 'webp', 'pdf'))]),
        ),
        migrations.AlterField(
            model_name='donation',
            name='proof',
            field=models.FileField(blank=True, storage=donations.storage.PrivateDonationStorage(), upload_to='donation_proofs/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg', 'png', 'webp', 'pdf'))]),
        ),
    ]
