# Generated by Django 5.2.17 on 2026-09-19 23:37

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RescueCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('animal_type', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('bird', 'Bird'), ('wildlife', 'Wildlife'), ('other', 'Other')], max_length=20)),
                ('animal_details', models.CharField(blank=True, max_length=255)),
                ('urgency', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('verified', 'Verified'), ('assigned', 'Assigned'), ('in_progress', 'In progress'), ('rescued', 'Rescued'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='reported', max_length=20)),
                ('contact_name', models.CharField(blank=True, max_length=150)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))])),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))])),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescue_cases', to='organizations.rescueorganization')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_rescue_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-reported_at',),
            },
        ),
        migrations.CreateModel(
            name='CaseStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('reported', 'Reported'), ('verified', 'Verified'), ('assigned', 'Assigned'), ('in_progress', 'In progress'), ('rescued', 'Rescued'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], max_length=20)),
                ('to_status', models.CharField(choices=[('reported', 'Reported'), ('verified', 'Verified'), ('assigned', 'Assigned'), ('in_progress', 'In progress'), ('rescued', 'Rescued'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescue_status_changes', to=settings.AUTH_USER_MODEL)),
                ('rescue_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='rescue.rescuecase')),
            ],
            options={
                'verbose_name_plural': 'case status histories',
                'ordering': ('-changed_at',),
            },
        ),
        migrations.CreateModel(
            name='RescueCaseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='rescue_cases/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg', 'png', 'webp'))])),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('rescue_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rescue.rescuecase')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_rescue_case_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('uploaded_at',),
            },
        ),
        migrations.CreateModel(
            name='RescueAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rescue_assignments', to=settings.AUTH_USER_MODEL)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rescue_assignments', to=settings.AUTH_USER_MODEL)),
                ('rescue_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='rescue.rescuecase')),
            ],
            options={
                'ordering': ('-assigned_at',),
                'constraints': [models.UniqueConstraint(fields=('rescue_case', 'assignee'), name='unique_rescue_case_assignee')],
            },
        ),
    ]
