# Generated by Django 5.2.17 on 2026-09-19 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestatushistory',
            name='from_status',
            field=models.CharField(blank=True, choices=[('reported', 'Đã báo tin'), ('verified', 'Đã xác minh'), ('assigned', 'Đã phân công'), ('in_progress', 'Đang cứu hộ'), ('rescued', 'Đã cứu thành công'), ('closed', 'Đã đóng'), ('cancelled', 'Đã hủy')], max_length=20),
        ),
        migrations.AlterField(
            model_name='casestatushistory',
            name='to_status',
            field=models.CharField(choices=[('reported', 'Đã báo tin'), ('verified', 'Đã xác minh'), ('assigned', 'Đã phân công'), ('in_progress', 'Đang cứu hộ'), ('rescued', 'Đã cứu thành công'), ('closed', 'Đã đóng'), ('cancelled', 'Đã hủy')], max_length=20),
        ),
        migrations.AlterField(
            model_name='rescuecase',
            name='animal_type',
            field=models.CharField(choices=[('dog', 'Chó'), ('cat', 'Mèo'), ('bird', 'Chim'), ('wildlife', 'Động vật hoang dã'), ('other', 'Khác')], max_length=20),
        ),
        migrations.AlterField(
            model_name='rescuecase',
            name='status',
            field=models.CharField(choices=[('reported', 'Đã báo tin'), ('verified', 'Đã xác minh'), ('assigned', 'Đã phân công'), ('in_progress', 'Đang cứu hộ'), ('rescued', 'Đã cứu thành công'), ('closed', 'Đã đóng'), ('cancelled', 'Đã hủy')], default='reported', max_length=20),
        ),
        migrations.AlterField(
            model_name='rescuecase',
            name='urgency',
            field=models.CharField(choices=[('low', 'Thấp'), ('medium', 'Trung bình'), ('high', 'Cao'), ('critical', 'Rất khẩn cấp')], default='medium', max_length=20),
        ),
    ]
