# Generated by Django 5.2.17 on 2026-09-20 00:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescue', '0004_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('case_claimed', 'Ca đã được tiếp nhận'), ('case_assigned', 'Ca đã được phân công'), ('status_changed', 'Trạng thái đã thay đổi'), ('case_updated', 'Nhật ký cứu hộ mới')], max_length=30),
        ),
        migrations.CreateModel(
            name='RescueUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescue_updates', to=settings.AUTH_USER_MODEL)),
                ('rescue_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='rescue.rescuecase')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RescueUpdateImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='rescue_updates/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg', 'png', 'webp'))])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rescue.rescueupdate')),
            ],
            options={
                'ordering': ('uploaded_at',),
            },
        ),
    ]
