# Generated by Django 5.2.17 on 2026-09-20 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescue', '0005_alter_notification_kind_rescueupdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('case_claimed', 'Ca đã được tiếp nhận'), ('case_assigned', 'Ca đã được phân công'), ('status_changed', 'Trạng thái đã thay đổi'), ('case_updated', 'Nhật ký cứu hộ mới'), ('adoption_submitted', 'Có đơn nhận nuôi mới'), ('adoption_reviewed', 'Đơn nhận nuôi đã được xét duyệt')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='rescue_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='rescue.rescuecase'),
        ),
    ]
