# Generated by Django 5.2.17 on 2026-09-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescue', '0008_alter_notification_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('case_claimed', 'Ca đã được tiếp nhận'), ('case_assigned', 'Ca đã được phân công'), ('status_changed', 'Trạng thái đã thay đổi'), ('case_updated', 'Nhật ký cứu hộ mới'), ('adoption_submitted', 'Có đơn nhận nuôi mới'), ('adoption_reviewed', 'Đơn nhận nuôi đã được xét duyệt'), ('adoption_safety', 'An toàn sau nhận nuôi'), ('support_message', 'Tin nhắn hỗ trợ'), ('donation_submitted', 'Có đóng góp mới'), ('donation_reviewed', 'Đóng góp đã được xác nhận')], max_length=30),
        ),
    ]
