# Generated by Django 5.2.17 on 2026-09-21 11:11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def seed_community_content(apps, schema_editor):
    contributor_model = apps.get_model('rescue', 'ContributorProfile')
    article_model = apps.get_model('rescue', 'KnowledgeArticle')

    contributors = [
        {
            'name': 'Nhóm điều phối hiện trường',
            'role': 'Tiếp nhận & xác minh',
            'bio': 'Kết nối người báo tin với tổ chức phù hợp, kiểm tra thông tin và ưu tiên những trường hợp khẩn cấp.',
            'static_image_path': 'images/community/volunteer-dogs.jpg',
            'photo_credit': 'Mia X / Pexels',
            'photo_source_url': 'https://www.pexels.com/photo/volunteer-feeding-rescued-dogs-at-animal-shelter-35231857/',
            'display_order': 1,
        },
        {
            'name': 'Nhóm chăm sóc tạm thời',
            'role': 'Foster & phục hồi',
            'bio': 'Hỗ trợ nơi ở tạm, theo dõi sức khỏe và giúp động vật làm quen lại với một môi trường an toàn.',
            'static_image_path': 'images/community/shelter-cat.jpg',
            'photo_credit': 'Artem Kniaz / Unsplash',
            'photo_source_url': 'https://unsplash.com/photos/a-cat-is-sitting-inside-of-a-small-window-AA0mTuZtGsw',
            'display_order': 2,
        },
        {
            'name': 'Nhóm truyền thông cộng đồng',
            'role': 'Kiến thức & kết nối',
            'bio': 'Biên soạn kiến thức dễ hiểu, lan tỏa các ca cần giúp và xây dựng một cộng đồng cứu hộ có trách nhiệm.',
            'static_image_path': 'images/community/kitten-shelter.jpg',
            'photo_credit': 'Eleni Trapp / Unsplash',
            'photo_source_url': 'https://unsplash.com/photos/a-tabby-kitten-reaches-for-a-latch-on-a-cage-x6Mx2mTY-1Y',
            'display_order': 3,
        },
    ]
    for contributor in contributors:
        contributor_model.objects.update_or_create(
            name=contributor['name'],
            defaults=contributor,
        )

    articles = [
        {
            'title': 'Gặp động vật bị thương: 5 bước an toàn đầu tiên',
            'slug': 'gap-dong-vat-bi-thuong-5-buoc-an-toan',
            'category': 'rescue',
            'excerpt': 'Giữ khoảng cách, ghi lại vị trí và gọi đúng người hỗ trợ trước khi chạm vào động vật đang hoảng sợ.',
            'body': '''1. Quan sát từ khoảng cách an toàn\n\nĐộng vật bị đau có thể cắn hoặc cào dù bình thường rất hiền. Trước tiên hãy kiểm tra giao thông, dây điện, nước sâu và những nguy hiểm quanh hiện trường.\n\n2. Ghi lại vị trí chính xác\n\nLưu địa chỉ, mốc dễ nhận biết hoặc ghim tọa độ. Nếu con vật di chuyển, hãy ghi lại hướng đi thay vì đuổi theo.\n\n3. Giữ trẻ em và thú nuôi ở xa\n\nTạo một khoảng trống yên tĩnh để giảm căng thẳng. Không tụ tập, chiếu đèn mạnh hoặc cố cho ăn khi chưa biết tình trạng.\n\n4. Chỉ di chuyển khi thật sự cần thiết\n\nVới con vật nhỏ, có thể dùng khăn dày và hộp thông khí nếu việc tiếp cận an toàn. Không tự bắt động vật lớn, hung dữ hoặc động vật hoang dã có khả năng gây nguy hiểm.\n\n5. Liên hệ bác sĩ thú y hoặc đội cứu hộ\n\nMô tả loài, kích thước, dấu hiệu chấn thương và vị trí. Làm theo hướng dẫn của người có chuyên môn trong lúc chờ hỗ trợ.''',
            'static_image_path': 'images/community/vet-kitten.jpg',
            'image_credit': 'Judy Beth Morris / Unsplash',
            'image_source_url': 'https://unsplash.com/photos/a-white-kitten-being-examined-by-a-veterinator-5Bi6MWlWMbw',
            'source_name': 'RSPCA — Injured wild animals',
            'source_url': 'https://www.rspca.org.uk/adviceandwelfare/wildlife/injured',
            'is_featured': True,
        },
        {
            'title': 'Nhận biết và sơ cứu sốc nhiệt ở chó mèo',
            'slug': 'nhan-biet-va-so-cuu-soc-nhiet-cho-meo',
            'category': 'health',
            'excerpt': 'Thở gấp, chảy dãi, lừ đừ hoặc mất thăng bằng có thể là cấp cứu. Làm mát đúng cách và gọi bác sĩ thú y ngay.',
            'body': '''Sốc nhiệt là một tình trạng cấp cứu\n\nCác dấu hiệu có thể gồm thở gấp bất thường, chảy nhiều dãi, lợi đỏ hoặc nhợt, nôn, yếu, lú lẫn, mất thăng bằng hay co giật. Đừng chờ các dấu hiệu tự hết.\n\nĐưa con vật ra khỏi nguồn nóng\n\nChuyển ngay tới nơi râm mát hoặc phòng thông thoáng. Tạo luồng gió bằng quạt hay điều hòa nếu có.\n\nBắt đầu làm mát\n\nDùng nước máy mát dội hoặc thấm lên cơ thể, tránh để nước đi vào mũi và miệng. Không trùm kín bằng khăn ướt vì khăn có thể giữ nhiệt. Cho uống từng ít nước nếu con vật tỉnh táo nhưng không ép uống.\n\nLiên hệ bác sĩ thú y ngay\n\nGọi cơ sở thú y trong lúc bắt đầu làm mát và làm theo chỉ dẫn. Ngay cả khi có vẻ hồi phục, con vật vẫn cần được kiểm tra vì tổn thương bên trong có thể xuất hiện muộn.''',
            'static_image_path': 'images/community/dog-cooling.jpg',
            'image_credit': 'Lucie Hošová / Unsplash',
            'image_source_url': 'https://unsplash.com/photos/dog-happily-cooling-off-in-the-water-5c8BlnGwmDI',
            'source_name': 'PDSA — First aid for heatstroke',
            'source_url': 'https://www.pdsa.org.uk/pet-help-and-advice/pet-health-hub/other-veterinary-advice/first-aid-for-heatstroke',
            'is_featured': False,
        },
        {
            'title': 'Chuẩn bị một hộp cứu hộ động vật cơ bản',
            'slug': 'chuan-bi-hop-cuu-ho-dong-vat-co-ban',
            'category': 'care',
            'excerpt': 'Một chiếc hộp thoáng khí, khăn dày, găng tay và thông tin liên hệ phù hợp giúp bạn ứng phó bình tĩnh hơn.',
            'body': '''Những vật dụng nên có\n\nChuẩn bị hộp hoặc lồng vận chuyển chắc chắn có lỗ thông khí, khăn dày, găng tay bảo hộ, đèn pin, túi rác, nước sạch và giấy để ghi thông tin. Không để thuốc của người trong hộp cứu hộ động vật.\n\nThông tin quan trọng không nên thiếu\n\nLưu sẵn số điện thoại bác sĩ thú y gần nhất, tổ chức cứu hộ địa phương và cơ quan phụ trách động vật hoang dã. Ghi lại vị trí chính xác nơi tìm thấy con vật vì việc thả về đúng khu vực có thể rất quan trọng.\n\nDùng hộp thế nào cho an toàn\n\nLót khăn, giữ hộp ở nơi tối, yên tĩnh và thông thoáng. Hạn chế mở hộp hoặc kiểm tra liên tục. Không tự cho ăn hay uống nếu chưa được người có chuyên môn hướng dẫn.\n\nBiết giới hạn của mình\n\nBộ dụng cụ giúp bạn hỗ trợ ban đầu, không biến bạn thành chuyên gia bắt giữ. Với động vật lớn, hung dữ, có nọc độc hoặc dấu hiệu bệnh truyền nhiễm, hãy giữ khoảng cách và gọi lực lượng phù hợp.''',
            'static_image_path': 'images/community/dog-water.jpg',
            'image_credit': 'R_ INVSCIMENTO / Unsplash',
            'image_source_url': 'https://unsplash.com/photos/a-dog-is-standing-in-the-cool-water-dZOn8GQ0jpU',
            'source_name': 'RSPCA — Become a Local Animal Hero',
            'source_url': 'https://www.rspca.org.uk/whatwedo/latest/kindnessindex/2025/onekind',
            'is_featured': False,
        },
    ]
    for article in articles:
        article_model.objects.update_or_create(
            slug=article['slug'],
            defaults=article,
        )


def remove_seed_community_content(apps, schema_editor):
    contributor_model = apps.get_model('rescue', 'ContributorProfile')
    article_model = apps.get_model('rescue', 'KnowledgeArticle')
    contributor_model.objects.filter(
        name__in=(
            'Nhóm điều phối hiện trường',
            'Nhóm chăm sóc tạm thời',
            'Nhóm truyền thông cộng đồng',
        )
    ).delete()
    article_model.objects.filter(
        slug__in=(
            'gap-dong-vat-bi-thuong-5-buoc-an-toan',
            'nhan-biet-va-so-cuu-soc-nhiet-cho-meo',
            'chuan-bi-hop-cuu-ho-dong-vat-co-ban',
        )
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('rescue', '0009_alter_notification_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('role', models.CharField(max_length=160)),
                ('bio', models.TextField(max_length=520)),
                ('photo', models.FileField(blank=True, upload_to='contributors/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg', 'png', 'webp'))])),
                ('static_image_path', models.CharField(blank=True, max_length=255)),
                ('photo_credit', models.CharField(blank=True, max_length=180)),
                ('photo_source_url', models.URLField(blank=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('display_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='KnowledgeArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(max_length=240, unique=True)),
                ('category', models.CharField(choices=[('rescue', 'Kỹ năng cứu hộ'), ('health', 'Sức khỏe thú cưng'), ('care', 'Chăm sóc an toàn')], max_length=20)),
                ('excerpt', models.TextField(max_length=420)),
                ('body', models.TextField()),
                ('cover_image', models.FileField(blank=True, upload_to='knowledge/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg', 'png', 'webp'))])),
                ('static_image_path', models.CharField(blank=True, max_length=255)),
                ('image_credit', models.CharField(blank=True, max_length=180)),
                ('image_source_url', models.URLField(blank=True)),
                ('source_name', models.CharField(blank=True, max_length=180)),
                ('source_url', models.URLField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-is_featured', '-published_at'),
            },
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('case_claimed', 'Ca đã được tiếp nhận'), ('case_assigned', 'Ca đã được phân công'), ('status_changed', 'Trạng thái đã thay đổi'), ('case_updated', 'Nhật ký cứu hộ mới'), ('adoption_submitted', 'Có đơn nhận nuôi mới'), ('adoption_reviewed', 'Đơn nhận nuôi đã được xét duyệt'), ('adoption_safety', 'An toàn sau nhận nuôi'), ('support_message', 'Tin nhắn hỗ trợ'), ('donation_submitted', 'Có đóng góp mới'), ('donation_reviewed', 'Đóng góp đã được xác nhận'), ('feedback_received', 'Có góp ý mới')], max_length=30),
        ),
        migrations.CreateModel(
            name='CommunityFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('category', models.CharField(choices=[('general', 'Góp ý chung'), ('feature', 'Đề xuất tính năng'), ('problem', 'Báo lỗi / vấn đề'), ('partnership', 'Đề nghị hợp tác')], default='general', max_length=20)),
                ('message', models.TextField(max_length=3000)),
                ('status', models.CharField(choices=[('new', 'Mới'), ('reviewed', 'Đã xem'), ('closed', 'Đã xử lý')], default='new', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-submitted_at',),
            },
        ),
        migrations.RunPython(
            seed_community_content,
            remove_seed_community_content,
        ),
    ]
