# Generated by Django 5.2.17 on 2026-09-28 03:38

import django.core.validators
import rescue.storage
import shutil
from pathlib import Path

from django.conf import settings
from django.db import migrations, models


def _relocate_images(apps, source_root, destination_root):
    file_fields = (
        (apps.get_model("rescue", "RescueCaseImage"), "image"),
        (apps.get_model("rescue", "RescueUpdateImage"), "image"),
    )
    source_root = Path(source_root).resolve()
    destination_root = Path(destination_root).resolve()
    for model, field_name in file_fields:
        for item in model.objects.exclude(**{field_name: ""}).iterator():
            relative_name = getattr(item, field_name).name
            source = (source_root / relative_name).resolve()
            destination = (destination_root / relative_name).resolve()
            if source_root not in source.parents or destination_root not in destination.parents:
                continue
            if not source.is_file():
                continue
            destination.parent.mkdir(parents=True, exist_ok=True)
            if destination.exists():
                source.unlink()
            else:
                shutil.move(str(source), str(destination))


def move_rescue_images_private(apps, schema_editor):
    _relocate_images(
        apps,
        settings.MEDIA_ROOT,
        settings.PRIVATE_RESCUE_MEDIA_ROOT,
    )


def restore_rescue_images_public(apps, schema_editor):
    _relocate_images(
        apps,
        settings.PRIVATE_RESCUE_MEDIA_ROOT,
        settings.MEDIA_ROOT,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('rescue', '0012_alter_notification_kind'),
    ]

    operations = [
        migrations.RunPython(
            move_rescue_images_private,
            restore_rescue_images_public,
        ),
        migrations.AlterField(
            model_name='rescuecaseimage',
            name='image',
            field=models.FileField(storage=rescue.storage.PrivateRescueStorage(), upload_to='rescue_cases/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg', 'png', 'webp'))]),
        ),
        migrations.AlterField(
            model_name='rescueupdateimage',
            name='image',
            field=models.FileField(storage=rescue.storage.PrivateRescueStorage(), upload_to='rescue_updates/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg', 'png', 'webp'))]),
        ),
    ]
